## CURVATURE
default:
  # libretro
  shader: crt/crt-geom
  # emulators using reshader 
  mednafen: GeomCRT@CRTGeom.fx
  m2emulator: GeomCRT@CRTGeom.fx
  supermodel: GeomCRT@CRTGeom.fx
  hypseus: GeomCRT@CRTGeom.fx
  daphne: GeomCRT@CRTGeom.fx  
  oricutron: GeomCRT@CRTGeom.fx
  applewin: GeomCRT@CRTGeom.fx
  gsplus: GeomCRT@CRTGeom.fx
  scummvm: GeomCRT@CRTGeom.fx
  simcoupe: GeomCRT@CRTGeom.fx
  demul: GeomCRT@CRTGeom.fx
  demul-old: GeomCRT@CRTGeom.fx
  bigpemu: GeomCRT@CRTGeom.fx
  phoenix: GeomCRT@CRTGeom.fx
  solarus: GeomCRT@CRTGeom.fx
  redream: GeomCRT@CRTGeom.fx
  raine: GeomCRT@CRTGeom.fx
  duckstation: GeomCRT@CRTGeom.fx
  mupen64: GeomCRT@CRTGeom.fx
  xemu: GeomCRT@CRTGeom.fx
# per system overrides  
3ds:
  shader: handheld/lcd-shader
dreamcast:
  shader: crt/crt-hyllian-3d
  redream: GeomCRT@CRTGeom.fx
gamegear:
  shader: crt-guest-dr-venom-fast
gba:
  shader: handheld/lcd-grid-v2-gba-color
gb:
  shader: handheld/gameboy
gb2players:
  shader: handheld/gameboy
gbc:
  shader: handheld/lcd-grid-v2-gbc-color
gbc2players:
  shader: handheld/lcd-grid-v2-gbc-color
gc:
  shader: crt/crt-hyllian-3d
lynx:
  shader: crt/crt-guest-dr-venom-fast
  mednafen: GeomCRT@CRTGeom.fx
nds:
  shader: handheld/lcd-grid-v2-nds-color
ngp:
  shader: handheld/zfast-lcd
ngpc:
  shader: handheld/zfast-lcd
ps2:
  shader: crt/crt-hyllian-3d
psp:
  shader: handheld/lcd-grid-v2-psp-color
psx:
  shader: crt/crt-hyllian-3d
  mednafen: GeomCRT@CRTGeom.fx
vectrex:
  shader: retro/sharp-bilinear-scanlines
virtualboy:
  shader: retro/sharp-bilinear-scanlines
wii:
  shader: crt/crt-hyllian-3d
wswan:
  shader: handheld/zfast-lcd
  mednafen: GeomCRT@CRTGeom.fx
wswanc:
  shader: handheld/zfast-lcd
  mednafen: GeomCRT@CRTGeom.fx

